# -*- coding: utf-8 -*-
"""tyre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRu5feWEhY0lh9SrSR8zpPWgAZtu4tSW
"""

import requests
import pandas as pd
import json

# Download all 4 datasets
urls = {
    "vehicles":       "https://regrip.s3.ap-south-1.amazonaws.com/uploads/vehicles+(1).json",
    "vehicle_tyres":  "https://regrip.s3.ap-south-1.amazonaws.com/uploads/tyre+details.json",
    "tyre_history":   "https://regrip.s3.ap-south-1.amazonaws.com/uploads/tyre_history_log.json",
    "reusable_tyres": "https://regrip.s3.ap-south-1.amazonaws.com/uploads/Reusable+tyre+list.json"
}

raw = {}
for name, url in urls.items():
    r = requests.get(url)
    raw[name] = r.json()
    print(f"{name}: {len(raw[name])} records loaded")

for name, data in raw.items():
    print(f"\n=== {name} ===")
    # Show first record to understand fields
    first = data[0] if isinstance(data, list) else list(data.values())[0]
    print(json.dumps(first, indent=2))

!pip install xgboost lightgbm scikit-learn pandas numpy -q

import requests
import pandas as pd
import numpy as np
import json
import warnings
warnings.filterwarnings('ignore')

print("All libraries ready.")

urls = {
    "vehicles":       "https://regrip.s3.ap-south-1.amazonaws.com/uploads/vehicles+(1).json",
    "vehicle_tyres":  "https://regrip.s3.ap-south-1.amazonaws.com/uploads/tyre+details.json",
    "tyre_history":   "https://regrip.s3.ap-south-1.amazonaws.com/uploads/tyre_history_log.json",
    "reusable_tyres": "https://regrip.s3.ap-south-1.amazonaws.com/uploads/Reusable+tyre+list.json"
}

raw = {}
for name, url in urls.items():
    r = requests.get(url)
    raw[name] = r.json()
    print(f"{name}: {len(raw[name])} records loaded")

#Clean vehicle_tyres

df_tyres = pd.DataFrame(raw["vehicle_tyres"])

cols = ["id", "vehicle_id", "position", "tyre_size", "brand_name",
        "model_name", "belt_pattern", "avg_nsd", "tyre_km",
        "construction_type", "current_status"]
df_tyres = df_tyres[cols].copy()

df_tyres.rename(columns={
    "id": "tyre_id",
    "brand_name": "brand",
    "model_name": "model",
    "belt_pattern": "pattern"
}, inplace=True)

# Standardise text
for col in ["brand", "model", "pattern", "tyre_size", "construction_type"]:
    df_tyres[col] = df_tyres[col].astype(str).str.strip().str.upper()

# Convert numerics
df_tyres["avg_nsd"] = pd.to_numeric(df_tyres["avg_nsd"], errors="coerce")
df_tyres["tyre_km"]  = pd.to_numeric(df_tyres["tyre_km"],  errors="coerce")
df_tyres["vehicle_id"] = df_tyres["vehicle_id"].astype(str)

# Drop rows with missing NSD
df_tyres.dropna(subset=["avg_nsd"], inplace=True)

print(f"Cleaned vehicle_tyres: {df_tyres.shape}")
print(df_tyres.head(3))

df_vehicles = pd.DataFrame(raw["vehicles"])

cols_v = ["id", "vehicle_no", "vehicle_km", "axles", "wheels_count",
          "manufacturer_name", "model_name", "vehicle_type", "road_application"]
df_vehicles = df_vehicles[cols_v].copy()

df_vehicles.rename(columns={
    "id": "vehicle_id",
    "model_name": "vehicle_model"
}, inplace=True)

df_vehicles["vehicle_id"] = df_vehicles["vehicle_id"].astype(str)
df_vehicles["vehicle_km"] = pd.to_numeric(df_vehicles["vehicle_km"], errors="coerce")

print(f"Cleaned vehicles: {df_vehicles.shape}")
print(df_vehicles.head(3))

df_history = pd.DataFrame(raw["tyre_history"])

cols_h = ["tyre_id", "vehicle_id", "avg_nsd", "standard_nsd",
          "tyre_km", "tyre_belt_pattern", "tyre_status", "action"]
df_history = df_history[cols_h].copy()

df_history["tyre_id"]      = df_history["tyre_id"].astype(str)
df_history["avg_nsd"]      = pd.to_numeric(df_history["avg_nsd"],      errors="coerce")
df_history["standard_nsd"] = pd.to_numeric(df_history["standard_nsd"], errors="coerce")
df_history["tyre_km"]      = pd.to_numeric(df_history["tyre_km"],      errors="coerce")

# Per-tyre historical features
hist_agg = df_history.groupby("tyre_id").agg(
    hist_avg_nsd    = ("avg_nsd",      "mean"),
    hist_min_nsd    = ("avg_nsd",      "min"),
    hist_max_nsd    = ("avg_nsd",      "max"),
    hist_std_nsd    = ("avg_nsd",      "std"),
    hist_max_km     = ("tyre_km",      "max"),
    standard_nsd    = ("standard_nsd", "first"),
    record_count    = ("avg_nsd",      "count")
).reset_index()

hist_agg["hist_std_nsd"] = hist_agg["hist_std_nsd"].fillna(0)

print(f"History aggregated: {hist_agg.shape}")
print(hist_agg.head(3))

df_reusable = pd.DataFrame(raw["reusable_tyres"])

cols_r = ["id", "tyre_size", "brand_name", "model_name",
          "belt_pattern", "avg_nsd", "tyre_km", "construction_type"]
df_reusable = df_reusable[cols_r].copy()

df_reusable.rename(columns={
    "id": "reusable_id",
    "brand_name": "brand",
    "model_name": "model",
    "belt_pattern": "pattern"
}, inplace=True)

for col in ["brand", "model", "pattern", "tyre_size", "construction_type"]:
    df_reusable[col] = df_reusable[col].astype(str).str.strip().str.upper()

df_reusable["avg_nsd"] = pd.to_numeric(df_reusable["avg_nsd"], errors="coerce")
df_reusable["tyre_km"] = pd.to_numeric(df_reusable["tyre_km"],  errors="coerce")
df_reusable.dropna(subset=["avg_nsd"], inplace=True)

print(f"Cleaned reusable_tyres: {df_reusable.shape}")
print(df_reusable.head(3))

# Merge worn tyres with vehicle info
df_master = df_tyres.merge(df_vehicles, on="vehicle_id", how="left")

# Merge with historical NSD stats
df_master["tyre_id"] = df_master["tyre_id"].astype(str)
df_master = df_master.merge(hist_agg, on="tyre_id", how="left")

# Fill missing hist columns for tyres with no history
for col in ["hist_avg_nsd","hist_min_nsd","hist_max_nsd","hist_std_nsd"]:
    df_master[col] = df_master[col].fillna(df_master["avg_nsd"])
df_master["standard_nsd"] = df_master["standard_nsd"].fillna(0)
df_master["record_count"]  = df_master["record_count"].fillna(0)

print(f"Master dataset shape: {df_master.shape}")
print(df_master.columns.tolist())

df_master.to_csv("cleaned_vehicle_tyres.csv", index=False)
print("\nSaved: cleaned_vehicle_tyres.csv")

rows = []

for _, worn in df_master.iterrows():
    worn_nsd   = worn["avg_nsd"]
    worn_brand = worn["brand"]
    worn_model = worn["model"]
    worn_pat   = worn["pattern"]
    worn_size  = worn["tyre_size"]

    for _, cand in df_reusable.iterrows():
        nsd_diff    = abs(worn_nsd - cand["avg_nsd"])
        nsd_sim     = 1 / (1 + nsd_diff)
        model_match = int(worn_model == cand["model"])
        brand_match = int(worn_brand == cand["brand"])
        pat_match   = int(worn_pat   == cand["pattern"])
        size_match  = int(worn_size  == cand["tyre_size"])


        km_diff     = abs(worn["tyre_km"] - cand["tyre_km"]) if pd.notna(cand["tyre_km"]) else 9999
        km_sim      = 1 / (1 + km_diff / 10000)

        nsd_headroom = cand["avg_nsd"] - worn_nsd

        # Scored label (strict priority order respected by weights)
        score = (nsd_sim    * 0.40 +
                 model_match * 0.30 +
                 brand_match * 0.20 +
                 pat_match   * 0.10)

        rows.append({
            # IDs
            "tyre_id":          worn["tyre_id"],
            "vehicle_id":       worn["vehicle_id"],
            "position":         worn["position"],
            "reusable_id":      cand["reusable_id"],
            # Features
            "nsd_similarity":   round(nsd_sim, 4),
            "nsd_diff":         round(nsd_diff, 2),
            "nsd_headroom":     round(nsd_headroom, 2),
            "model_match":      model_match,
            "brand_match":      brand_match,
            "pattern_match":    pat_match,
            "size_match":       size_match,
            "km_similarity":    round(km_sim, 4),
            "worn_nsd":         worn_nsd,
            "candidate_nsd":    cand["avg_nsd"],
            "worn_km":          worn["tyre_km"],
            "candidate_km":     cand["tyre_km"],
            # Target
            "score":            round(score, 4)
        })

df_pairs = pd.DataFrame(rows)
df_pairs.to_csv("pairwise_dataset.csv", index=False)
print(f"Saved: pairwise_dataset.csv — {len(df_pairs):,} pairs")
print(df_pairs.head(5))

#from google.colab import files
#files.download("cleaned_vehicle_tyres.csv")
#files.download("pairwise_dataset.csv")

import pandas as pd
import numpy as np
from sklearn.model_selection import GroupShuffleSplit

df = pd.read_csv("pairwise_dataset.csv")

df["nsd_score"] = np.exp(-0.8 * df["nsd_diff"])
# nsd_diff=0   → nsd_score=1.0  (perfect match)
# nsd_diff=0.5 → nsd_score=0.37
# nsd_diff=1   → nsd_score=0.14
# nsd_diff=2   → nsd_score=0.02 (almost worthless)

df["tiebreaker"] = (
    df["model_match"]   * 0.20 +
    df["brand_match"]   * 0.12 +
    df["pattern_match"] * 0.05 +
    df["size_match"]    * 0.03
)

# tiebreaker fills remaining 0.30 only when NSD is already good
df["score"] = df["nsd_score"] * 0.65 + df["tiebreaker"] * 0.35

# Normalise to 0–1
df["score"] = (df["score"] - df["score"].min()) / (df["score"].max() - df["score"].min())

df["nsd_x_model"]   = df["nsd_similarity"] * df["model_match"]   * 3.0
df["nsd_x_brand"]   = df["nsd_similarity"] * df["brand_match"]   * 2.0
df["nsd_x_pattern"] = df["nsd_similarity"] * df["pattern_match"] * 1.0


print("Score distribution:")
print(df["score"].describe().round(4))
print(f"\nCorrelation of features with score:")
for f in ["nsd_similarity","nsd_diff","model_match","brand_match","pattern_match"]:
    print(f"  {f:20s}: {df[f].corr(df['score']):+.4f}")


# Features the model will use
FEATURES = [
    "nsd_similarity",   # Most important — NSD closeness
    "nsd_diff",         # Raw NSD difference
    "nsd_headroom",     # How much tread life candidate still has
    "model_match",      # Exact model match (binary)
    "brand_match",      # Same brand (binary)
    "pattern_match",    # Same belt pattern (binary)
    "size_match",       # Same tyre size (binary)
    "km_similarity",    # Similar usage km
    "worn_nsd",         # Actual NSD of worn tyre
    "candidate_nsd",    # Actual NSD of candidate
]

LGB_FEATURES = [
    "nsd_similarity",
    "nsd_diff",
    "nsd_headroom",
    "nsd_x_model",
    "nsd_x_brand",
    "nsd_x_pattern",
    "model_match",
    "brand_match",
    "pattern_match",
    "size_match",
    "km_similarity",
    "worn_nsd",
    "candidate_nsd"
]

X = df[FEATURES]
y = df["score"]
groups = df["tyre_id"]

# Split so no tyre_id appears in both train and test
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
df_test = df.iloc[test_idx].copy()  # Keep full test rows for Top-K evaluation

print(f"Train size: {len(X_train):,} rows")
print(f"Test size:  {len(X_test):,} rows")
print(f"Unique worn tyres in test: {df_test['tyre_id'].nunique()}")

import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score

model = xgb.XGBRegressor(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,          # (prevents overfitting)
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_train, y_train,
    eval_set=[(X_test, y_test)],
    verbose=50              # Print progress every 50 trees
)

# Basic regression metrics
y_pred = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2   = r2_score(y_test, y_pred)

print(f"\nRMSE: {rmse:.4f}  (lower is better, max possible error is 1.0)")
print(f"R²:   {r2:.4f}   (closer to 1.0 is better)")

results = []

for tyre_id, group in df_test.groupby("tyre_id"):
    group = group.copy()
    group["predicted_score"] = model.predict(X_test.loc[group.index])

    # Ground truth: the candidate with the highest formula score
    true_best = group.loc[group["score"].idxmax(), "reusable_id"]

    # Model's ranked list
    ranked = group.sort_values("predicted_score", ascending=False)
    top1 = ranked.iloc[0]["reusable_id"]
    top3 = ranked.iloc[:3]["reusable_id"].tolist()

    results.append({
        "tyre_id":    tyre_id,
        "true_best":  true_best,
        "top1_hit":   int(true_best == top1),
        "top3_hit":   int(true_best in top3)
    })

df_results = pd.DataFrame(results)
top1_acc = df_results["top1_hit"].mean() * 100
top3_acc = df_results["top3_hit"].mean() * 100

print(f"Top-1 Accuracy: {top1_acc:.1f}%")
print(f"Top-3 Accuracy: {top3_acc:.1f}%")

import matplotlib.pyplot as plt

importance = pd.Series(
    model.feature_importances_,
    index=FEATURES
).sort_values(ascending=True)

plt.figure(figsize=(8, 5))
importance.plot(kind="barh", color="steelblue")
plt.title("Feature Importance — XGBoost")
plt.xlabel("Importance score")
plt.tight_layout()
plt.savefig("feature_importance.png", dpi=150)
plt.show()

print("\nFeature importance ranking:")
print(importance.sort_values(ascending=False))

import joblib, json

joblib.dump(model, "tyre_model.pkl")
print("Model saved.")

# Reload fresh to avoid type mismatch issues
df_pairs    = pd.read_csv("pairwise_dataset.csv")
df_reusable = pd.read_csv("cleaned_vehicle_tyres.csv")

# Ensure tyre_id is string in both
df_pairs["tyre_id"]    = df_pairs["tyre_id"].astype(str)
df_reusable["tyre_id"] = df_reusable["tyre_id"].astype(str)

FEATURES = [
    "nsd_similarity", "nsd_diff", "nsd_headroom",
    "model_match", "brand_match", "pattern_match",
    "size_match", "km_similarity", "worn_nsd", "candidate_nsd"
]

def predict_for_tyre(tyre_id, top_k=5):
    tyre_id = str(tyre_id)
    candidates = df_pairs[df_pairs["tyre_id"] == tyre_id].copy()

    if candidates.empty:
        # Show available IDs to help debug
        available = df_pairs["tyre_id"].unique()[:10]
        return {"error": f"tyre_id '{tyre_id}' not found. Sample available IDs: {list(available)}"}

    candidates["predicted_score"] = model.predict(candidates[FEATURES])
    candidates = candidates.sort_values("predicted_score", ascending=False).head(top_k)

    recommendations = []
    for _, row in candidates.iterrows():
        reasons = []
        if row["nsd_diff"] <= 1:   reasons.append("closest NSD")
        if row["model_match"]:     reasons.append("same model")
        if row["brand_match"]:     reasons.append("same brand")
        if row["pattern_match"]:   reasons.append("same pattern")
        if not reasons:            reasons.append("good NSD match")

        recommendations.append({
            "reusable_tyre_id": str(int(row["reusable_id"])),
            "score":            round(float(row["predicted_score"]), 4),
            "reason":           " + ".join(reasons)
        })

    meta = candidates.iloc[0]
    return {
        "tyre_id":         tyre_id,
        "vehicle_id":      str(meta["vehicle_id"]),
        "position":        str(meta["position"]),
        "recommendations": recommendations
    }

# ── Test with a real tyre_id from the dataset ──
sample_id = df_pairs["tyre_id"].iloc[0]
print(f"Testing with tyre_id: {sample_id}")

result = predict_for_tyre(sample_id, top_k=5)
print(json.dumps(result, indent=2))

with open("sample_prediction.json", "w") as f:
    json.dump(result, f, indent=2)
print("\nSaved: sample_prediction.json")

result = predict_for_tyre("78346", top_k=3)
print(json.dumps(result, indent=2))

#Trying KNN

from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, r2_score

scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)


k_values = [3, 5, 7, 10, 15, 20]
k_results = []

print("Finding best K...")
print(f"{'K':>5} | {'RMSE':>8} | {'R²':>8}")
print("-" * 28)

for k in k_values:
    knn = KNeighborsRegressor(n_neighbors=k, metric="euclidean", n_jobs=-1)
    knn.fit(X_train_scaled, y_train)
    preds = knn.predict(X_test_scaled)
    rmse  = np.sqrt(mean_squared_error(y_test, preds))
    r2    = r2_score(y_test, preds)
    k_results.append({"k": k, "rmse": rmse, "r2": r2, "model": knn})
    print(f"{k:>5} | {rmse:>8.4f} | {r2:>8.4f}")

# Pick best K by lowest RMSE
best = min(k_results, key=lambda x: x["rmse"])
best_knn = best["model"]
print(f"\nBest K = {best['k']}  (RMSE={best['rmse']:.4f})")

knn_results = []

for tyre_id, group in df_test.groupby("tyre_id"):
    group = group.copy()
    group_scaled = scaler.transform(group[FEATURES])
    group["knn_score"] = best_knn.predict(group_scaled)

    true_best = group.loc[group["score"].idxmax(), "reusable_id"]
    ranked    = group.sort_values("knn_score", ascending=False)
    top1      = ranked.iloc[0]["reusable_id"]
    top3      = ranked.iloc[:3]["reusable_id"].tolist()

    knn_results.append({
        "tyre_id":  tyre_id,
        "true_best": true_best,
        "top1_hit":  int(true_best == top1),
        "top3_hit":  int(true_best in top3)
    })

df_knn_results = pd.DataFrame(knn_results)
knn_top1 = df_knn_results["top1_hit"].mean() * 100
knn_top3 = df_knn_results["top3_hit"].mean() * 100

print(f"KNN Top-1 Accuracy: {knn_top1:.1f}%")
print(f"KNN Top-3 Accuracy: {knn_top3:.1f}%")

!pip install lightgbm -q

import lightgbm as lgb
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("LightGBM version:", lgb.__version__)

lgb_model = lgb.LGBMRegressor(
    n_estimators=1000,
    max_depth=6,
    learning_rate=0.03,
    num_leaves=31,
    min_child_samples=20,
    subsample=0.8,
    reg_alpha=0.1,
    reg_lambda=1.0,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
    verbose=-1
)
if "nsd_x_model" not in df.columns:
    df["nsd_x_model"]   = df["nsd_similarity"] * df["model_match"]   * 3.0
    df["nsd_x_brand"]   = df["nsd_similarity"] * df["brand_match"]   * 2.0
    df["nsd_x_pattern"] = df["nsd_similarity"] * df["pattern_match"] * 1.0



X_train_lgb = df.iloc[train_idx][LGB_FEATURES]
X_test_lgb  = df.iloc[test_idx][LGB_FEATURES]

lgb_model.fit(
    X_train_lgb, y_train,
    eval_set=[(X_test_lgb, y_test)],
    callbacks=[lgb.early_stopping(50, verbose=False),
               lgb.log_evaluation(100)]
)

lgb_preds = lgb_model.predict(X_test_lgb)
rmse_lgb  = np.sqrt(mean_squared_error(y_test, lgb_preds))
r2_lgb    = r2_score(y_test, lgb_preds)

print(f"LightGBM RMSE: {rmse_lgb:.4f}")
print(f"LightGBM R²:   {r2_lgb:.4f}")
print(f"Best iteration: {lgb_model.best_iteration_}")

lgb_results = []

for tyre_id, group in df_test.groupby("tyre_id"):
    group = group.copy()
    group["lgb_score"] = lgb_model.predict(group[LGB_FEATURES])

    true_best = group.loc[group["score"].idxmax(), "reusable_id"]
    ranked    = group.sort_values("lgb_score", ascending=False)
    top1      = ranked.iloc[0]["reusable_id"]
    top3      = ranked.iloc[:3]["reusable_id"].tolist()

    lgb_results.append({
        "tyre_id":  tyre_id,
        "top1_hit": int(true_best == top1),
        "top3_hit": int(true_best in top3)
    })

df_lgb    = pd.DataFrame(lgb_results)
lgb_top1  = df_lgb["top1_hit"].mean() * 100
lgb_top3  = df_lgb["top3_hit"].mean() * 100

print(f"LightGBM Top-1 Accuracy: {lgb_top1:.1f}%")
print(f"LightGBM Top-3 Accuracy: {lgb_top3:.1f}%")

# Plot feature importance for the enhanced LightGBM model
lgb_importance = pd.Series(
    lgb_model.booster_.feature_importance(importance_type="gain"),
    index=LGB_FEATURES
).sort_values(ascending=False)

lgb_importance = lgb_importance / lgb_importance.sum()

print("Enhanced LightGBM feature importance (gain-based):")
print(lgb_importance.round(4))

plt.figure(figsize=(8, 5))
lgb_importance.sort_values().plot(kind="barh", color="darkgreen")
plt.title("Feature Importance — Enhanced LightGBM")
plt.xlabel("Importance score (normalised)")
plt.tight_layout()
plt.savefig("feature_importance_lgbm_enhanced.png", dpi=150)
plt.show()





# Final model comparison including the original and enhanced LightGBM

models_final    = ["XGBoost", "KNN", "LightGBM"]
top1_vals_final = [top1_acc, knn_top1, lgb_top1]
top3_vals_final = [top3_acc, knn_top3, lgb_top3]

x_final = np.arange(len(models_final))
width = 0.20

fig_final, ax_final = plt.subplots(figsize=(12, 7)) # Larger figure
bars1_final = ax_final.bar(x_final - width/2, top1_vals_final, width, label="Top-1 Accuracy", color="#2196F3")
bars2_final = ax_final.bar(x_final + width/2, top3_vals_final, width, label="Top-3 Accuracy", color="#4CAF50")

ax_final.set_ylabel("Accuracy (%)")
ax_final.set_title("Model Comparison — XGBoost vs KNN vs LightGBM")
ax_final.set_xticks(x_final)
ax_final.set_xticklabels(models_final, rotation=45, ha="right")
ax_final.set_ylim(0, 110)
ax_final.legend()
ax_final.bar_label(bars1_final, fmt="%.1f%%", padding=3)
ax_final.bar_label(bars2_final, fmt="%.1f%%", padding=3)

plt.tight_layout()
plt.savefig("model_comparison_all_models.png", dpi=150)
plt.show()

print("\nFinal comparison of all models:")
print(f"{'Model':>20} | {'Top-1':>8} | {'Top-3':>8}")
print("-" * 43)
print(f"{'XGBoost':>20} | {top1_acc:>7.1f}% | {top3_acc:>7.1f}%")
print(f"{'KNN':>20} | {knn_top1:>7.1f}% | {knn_top3:>7.1f}%")
print(f"{'LightGBM':>20} | {lgb_top1:>7.1f}% | {lgb_top3:>7.1f}%")

LGB_FEATURES = [
    "nsd_similarity",
    "nsd_diff",
    "nsd_headroom",
    "nsd_x_model",
    "nsd_x_brand",
    "nsd_x_pattern",
    "model_match",
    "brand_match",
    "pattern_match",
    "size_match",
    "km_similarity",
    "worn_nsd",
    "candidate_nsd"
]
def predict_for_tyre_lgbm(tyre_id, top_k=5):
    tyre_id = str(tyre_id)
    candidates = df_pairs[df_pairs["tyre_id"] == tyre_id].copy()

    if candidates.empty:
        available = df_pairs["tyre_id"].unique()[:10]
        return {"error": f"tyre_id '{tyre_id}' not found. Sample available IDs: {list(available)}"}

    candidates["nsd_score"] = np.exp(-0.8 * candidates["nsd_diff"])
    candidates["nsd_x_model"]   = candidates["nsd_similarity"] * candidates["model_match"]   * 3.0
    candidates["nsd_x_brand"]   = candidates["nsd_similarity"] * candidates["brand_match"]   * 2.0
    candidates["nsd_x_pattern"] = candidates["nsd_similarity"] * candidates["pattern_match"] * 1.0

    # Use the LightGBM model and its specific features
    candidates["predicted_score"] = lgb_model.predict(candidates[LGB_FEATURES])
    candidates = candidates.sort_values("predicted_score", ascending=False).head(top_k)

    recommendations = []
    for _, row in candidates.iterrows():
        reasons = []
        if row["nsd_diff"] <= 1:   reasons.append("closest NSD")
        if row["model_match"]:     reasons.append("same model")
        if row["brand_match"]:     reasons.append("same brand")
        if row["pattern_match"]:   reasons.append("same pattern")
        if not reasons:            reasons.append("good NSD match")

        recommendations.append({
            "reusable_tyre_id": str(int(row["reusable_id"])),
            "score":            round(float(row["predicted_score"]), 4),
            "reason":           " + ".join(reasons)
        })

    meta = candidates.iloc[0]
    return {
        "tyre_id":         tyre_id,
        "vehicle_id":      str(meta["vehicle_id"]),
        "position":        str(meta["position"]),
        "recommendations": recommendations
    }

# ── Test with a real tyre_id from the dataset ──
sample_id = df_pairs["tyre_id"].iloc[0]
print(f"Testing LightGBM with tyre_id: {sample_id}")

result_lgbm = predict_for_tyre_lgbm(sample_id, top_k=5)
print(json.dumps(result_lgbm, indent=2))

with open("sample_prediction_lgbm.json", "w") as f:
    json.dump(result_lgbm, f, indent=2)
print("\nSaved: sample_prediction_lgbm.json")

"""
predict.py — Tyre Replacement Recommendation Script
Usage: python predict.py --tyre_id 14201 --top_k 5
"""

import pandas as pd
import numpy as np
import joblib
import json
import argparse

# ── Load model and data ───────────────────────────────────
model     = joblib.load("tyre_model.pkl")
df_pairs  = pd.read_csv("pairwise_dataset.csv")
df_pairs["tyre_id"] = df_pairs["tyre_id"].astype(str)

FEATURES = [
    "nsd_similarity", "nsd_diff", "nsd_headroom",
    "model_match", "brand_match", "pattern_match",
    "size_match", "km_similarity", "worn_nsd", "candidate_nsd"
]

# ── Prediction function ───────────────────────────────────
def predict_for_tyre(tyre_id, top_k=5):
    tyre_id    = str(tyre_id)
    candidates = df_pairs[df_pairs["tyre_id"] == tyre_id].copy()

    if candidates.empty:
        return {"error": f"tyre_id {tyre_id} not found"}

    candidates["predicted_score"] = model.predict(candidates[FEATURES])
    candidates = candidates.sort_values("predicted_score", ascending=False).head(top_k)

    recommendations = []
    for _, row in candidates.iterrows():
        reasons = []
        if row["nsd_diff"] <= 1:   reasons.append("closest NSD")
        if row["model_match"]:     reasons.append("same model")
        if row["brand_match"]:     reasons.append("same brand")
        if row["pattern_match"]:   reasons.append("same pattern")
        if not reasons:            reasons.append("good NSD match")

        recommendations.append({
            "reusable_tyre_id": str(int(row["reusable_id"])),
            "score":            round(float(row["predicted_score"]), 4),
            "reason":           " + ".join(reasons)
        })

    meta = candidates.iloc[0]
    return {
        "tyre_id":         tyre_id,
        "vehicle_id":      str(meta["vehicle_id"]),
        "position":        str(meta["position"]),
        "recommendations": recommendations
    }

# ── Run ───────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--tyre_id", required=True)
    parser.add_argument("--top_k",   type=int, default=5)
    args = parser.parse_args()

    result = predict_for_tyre(args.tyre_id, args.top_k)
    print(json.dumps(result, indent=2))





